services:
  db-ouranos:
    container_name: db-ouranos
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    restart: always
    ports:
      - "27018:27017"
    privileged: true
    volumes:
      - db-talos-data-cni:/etc/cni
      - db-talos-data-containers:/var/lib/containers
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  messaging-ouranos:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  pantheon-gateway:
    container_name: pantheon-gateway
    image: registry.gitlab.com/talos8645929/ouranos-pantheon/pantheon-gateway:latest
    ports:
      - "8300:8300"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8300
      Ouranos__IncludeExceptionDetails: true
      Ouranos__RequestTimeout: 180
      Ouranos__Mongo__ConnectionString: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db-ouranos:27017?authSource=admin
      Ouranos__OuranosMl__ConnectionString: ${OURANOS_ML_URL}
  
  pantheon-plutus-data-loader-consumer:
    container_name: pantheon-plutus-data-loader-consumer
    image: registry.gitlab.com/talos8645929/ouranos-pantheon/pantheon-plutus-data-loader-consumer:latest
    environment:
      Ouranos__Mongo__ConnectionString: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db-ouranos:27017?authSource=admin
      Ouranos__RabbitMq__Username: ${RABBITMQ_USERNAME}
      Ouranos__RabbitMq__Password: ${RABBITMQ_PASSWORD}

  pantheon-plutus-data-loader-ffxiv:
    container_name: pantheon-plutus-data-loader-ffxiv
    image: registry.gitlab.com/talos8645929/ouranos-pantheon/pantheon-plutus-data-loader-ffxiv:latest
    environment:
      Ouranos__RabbitMq__Username: ${RABBITMQ_USERNAME}
      Ouranos__RabbitMq__Password: ${RABBITMQ_PASSWORD}

  pantheon-plutus-data-loader-osrs:
    container_name: pantheon-plutus-data-loader-osrs
    image: registry.gitlab.com/talos8645929/ouranos-pantheon/pantheon-plutus-data-loader-osrs:latest
    environment:
      Ouranos__RabbitMq__Username: ${RABBITMQ_USERNAME}
      Ouranos__RabbitMq__Password: ${RABBITMQ_PASSWORD}

  # Enable after Legacy Talos app is shutdown.
  # pantheon-plutus-data-loader-stocks:
  #   container_name: pantheon-plutus-data-loader-stocks
  #   image: registry.gitlab.com/talos8645929/ouranos-pantheon/pantheon-plutus-data-loader-stocks:latest
  #   environment:
  #     Ouranos__Alpaca__ApiKey: ${ALPACA_API_KEY}
  #     Ouranos__Alpaca__ApiSecret: ${ALPACA_API_SECRET}
  #     Ouranos__RabbitMq__Username: ${RABBITMQ_USERNAME}
  #     Ouranos__RabbitMq__Password: ${RABBITMQ_PASSWORD}

  # Enable when interface is ready.
  #pantheon-interface:
  #  image: registry.gitlab.com/talos8645929/ouranos-pantheon/pantheon-interface:latest
  #  ports:
  #    - "8080:80"

volumes:
  db-talos-data-cni:
  db-talos-data-containers:
