services:
  db-ouranos:
    container_name: db-ouranos
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    restart: always
    ports:
      - "27018:27017"
    privileged: true
    volumes:
      - db-talos-data-cni:/etc/cni
      - db-talos-data-containers:/var/lib/containers
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  pantheon-gateway:
    container_name: pantheon-gateway
    image: registry.gitlab.com/talos8645929/ouranos-pantheon/pantheon-gateway:latest
    ports:
      - "8300:8300"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8300
      Ouranos__IncludeExceptionDetails: true
      Mongo__ConnectionString: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db-ouranos:27017?authSource=admin
      Hermes__OuranosMl__ConectionString: ${OURANOS_ML_URL}

  #pantheon-interface:
  #  image: registry.gitlab.com/talos8645929/ouranos-pantheon/pantheon-interface:latest
  #  ports:
  #    - "8080:80"

volumes:
  db-talos-data-cni:
  db-talos-data-containers:
