services:
  db-talos:
    container_name: db-talos
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    restart: always
    ports:
      - "27018:27017"
    privileged: true
    volumes:
      - db-talos-data-cni:/etc/cni
      - db-talos-data-containers:/var/lib/containers
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  aphrodite-service:
    container_name: aphrodite-service
    image: registry.gitlab.com/talos8645929/talos-olympus/aphrodite-service:latest
    depends_on:
      - db-talos
    ports:
      - "8301:8301"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8301
      Talos__IncludeExceptionDetails: true
      MONGO_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db-talos:27017/aphrodite?authSource=admin
      TALOS_ML_URL: ${TALOS_ML_URL}

  plutus-service:
    container_name: plutus-service
    image: registry.gitlab.com/talos8645929/talos-olympus/plutus-service:latest
    depends_on:
      - db-talos
    ports:
      - "8302:8302"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8302
      Talos__IncludeExceptionDetails: true
      MONGO_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db-talos:27017/plutus?authSource=admin

  talos-gateway:
    container_name: talos-gateway
    image: registry.gitlab.com/talos8645929/talos-olympus/gateway:latest
    depends_on:
      - plutus-service
      - aphrodite-service
    ports:
      - "8300:8300"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8300
      Talos__IncludeExceptionDetails: true

  #talos-interface:
  #  image: registry.gitlab.com/talos/talos-interface:main
  #  ports:
  #    - "8080:80"

volumes:
  db-talos-data-cni:
  db-talos-data-containers:
