x-service-policy: &service-policy
  restart: always

services:
  pantheon-db:
    <<: *service-policy
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - "27018:27017"
    privileged: true
    volumes:
      - pantheon-db-data-cni:/etc/cni
      - pantheon-db-data-containers:/var/lib/containers
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  pantheon-psql-db:
    <<: *service-policy
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_DB: pantheon
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pantheon-psql-db:/var/lib/postgresql/data

  pantheon-messaging:
    <<: *service-policy
    image: rabbitmq:3-management-alpine
    hostname: pantheon-messaging
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_shovel rabbitmq_shovel_management &&
             rabbitmq-server"

  pantheon-gateway:
    <<: *service-policy
    image: registry.gitlab.com/talos8645929/ouranos-pantheon/pantheon-gateway:latest
    ports:
      - "8300:8300"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8300
      Ouranos__IncludeExceptionDetails: true
      Ouranos__RequestTimeout: 180
      Ouranos__Mongo__ConnectionString: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@pantheon-db:27017?authSource=admin
      Ouranos__Postgres__Host: ouranos-psql-db
      Ouranos__Postgres__Username: ${POSTGRES_USER}
      Ouranos__Postgres__Password: ${POSTGRES_PASSWORD}
      Ouranos__OuranosMl__ConnectionString: ${OURANOS_ML_URL}
      Ouranos__Hermes__OuranosMl__SystemPrompt: ${HERMES_SYSTEM_PROMPT}

  pantheon-plutus-data-loader-consumer:
    <<: *service-policy
    image: registry.gitlab.com/talos8645929/ouranos-pantheon/pantheon-plutus-data-loader-consumer:latest
    environment:
      DOTNET_ENVIRONMENT: Production
      Ouranos__Mongo__ConnectionString: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@pantheon-db:27017?authSource=admin
      Ouranos__Postgres__Host: ouranos-psql-db
      Ouranos__Postgres__Username: ${POSTGRES_USER}
      Ouranos__Postgres__Password: ${POSTGRES_PASSWORD}
      Ouranos__RabbitMq__Host: pantheon-messaging
      Ouranos__RabbitMq__Username: ${RABBITMQ_USERNAME}
      Ouranos__RabbitMq__Password: ${RABBITMQ_PASSWORD}

  pantheon-plutus-data-loader-ffxiv:
    <<: *service-policy
    image: registry.gitlab.com/talos8645929/ouranos-pantheon/pantheon-plutus-data-loader-ffxiv:latest
    environment:
      DOTNET_ENVIRONMENT: Production
      Ouranos__RabbitMq__Host: pantheon-messaging
      Ouranos__RabbitMq__Username: ${RABBITMQ_USERNAME}
      Ouranos__RabbitMq__Password: ${RABBITMQ_PASSWORD}

  pantheon-plutus-data-loader-osrs:
    <<: *service-policy
    image: registry.gitlab.com/talos8645929/ouranos-pantheon/pantheon-plutus-data-loader-osrs:latest
    environment:
      DOTNET_ENVIRONMENT: Production
      Ouranos__RabbitMq__Host: pantheon-messaging
      Ouranos__RabbitMq__Username: ${RABBITMQ_USERNAME}
      Ouranos__RabbitMq__Password: ${RABBITMQ_PASSWORD}
      Ouranos__OsrsWiki__UserAgent: ${OSRS_WIKI_USER_AGENT}

  pantheon-plutus-data-loader-stocks:
    <<: *service-policy
    image: registry.gitlab.com/talos8645929/ouranos-pantheon/pantheon-plutus-data-loader-stocks:latest
    environment:
      DOTNET_ENVIRONMENT: Production
      Ouranos__Alpaca__ApiKey: ${ALPACA_API_KEY}
      Ouranos__Alpaca__ApiSecret: ${ALPACA_API_SECRET}
      Ouranos__RabbitMq__Host: pantheon-messaging
      Ouranos__RabbitMq__Username: ${RABBITMQ_USERNAME}
      Ouranos__RabbitMq__Password: ${RABBITMQ_PASSWORD}

  pantheon-interface:
    <<: *service-policy
    image: registry.gitlab.com/talos8645929/ouranos-pantheon/pantheon-interface:latest
    ports:
      - "80:3000"

volumes:
  pantheon-db-data-cni:
  pantheon-db-data-containers:
  rabbitmq_data:
  rabbitmq_logs:
  pantheon-psql-db:
