log:
  level: info
  job_level: info

runner:
  file: .runner
  capacity: 1
  env_file: .env
  timeout: 3h
  shutdown_timeout: 3h
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 2s
  report_interval: 1s
  labels: ["ubuntu-latest:docker:ghcr.io/catthehacker/ubuntu:runner-latest"]

cache:
  enabled: true
  port: 0
  dir: ""
  external_server: ""
  secret: ""
  host: ""
  proxy_port: 0
  actions_cache_url_override: ""

container:
  network: "host"
  enable_ipv6: false
  privileged: true
  options:
  workdir_parent:
  valid_volumes: []
  docker_host: "tcp://forgejo-dind:2375"
  force_pull: false
  force_rebuild: false

host:
  workdir_parent:
