services:
  postgres:
    image: timescale/timescaledb:2.21.1-pg17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  db-init:
    image: timescale/timescaledb:2.21.1-pg17
    environment:
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGHOST: postgres
      INIT_DATABASES: pantheon, flagsmith
    volumes:
      - ./init-databases.sh:/init-databases.sh:Z
    command: ["/bin/bash", "/init-databases.sh"]
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:
