# See https://forgejo.org/docs/next/admin/actions/runner-installation for setup instructions.

services:
  forejo-dind:
    image: docker:dind
    privileged: "true"
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false"]
    restart: "unless-stopped"

  forejo-runner:
    image: "data.forgejo.org/forgejo/runner:11"
    links:
      - forejo-dind
    depends_on:
      forejo-dind:
        condition: service_started
    environment:
      DOCKER_HOST: tcp://forejo-dind:2375
    user: 1001:1001
    volumes:
      - ~/.local/share/forejo-runner:/data
    restart: "unless-stopped"

    command: '/bin/sh -c "while : ; do sleep 1 ; done ;"'
