x-service-policy: &service-policy
  restart: unless-stopped

services:
  runner-dind:
    <<: *service-policy
    image: docker:dind
    privileged: "true"
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false"]

  github-runner:
    <<: *service-policy
    image: "myoung34/github-runner:2.336.0-ubuntu-jammy"
    links:
      - runner-dind
    depends_on:
      runner-dind:
        condition: service_started
    environment:
      REPO_URL: https://github.com/davwales/ouranos-infrastructure
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      RUNNER_NAME: ouranos-runner
      LABELS: self-hosted,linux,docker
      DOCKER_HOST: tcp://runner-dind:2375
    volumes:
      - runner_data:/actions-runner

volumes:
  runner_data:
